# Generated by Django 5.0.2 on 2025-09-13 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('descar', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='DescAr', max_length=50, null=True)),
                ('descen', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='DescEn', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Jobs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('fullname', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='FullName', max_length=50, null=True)),
                ('birthdate', models.DateTimeField(blank=True, db_column='Birthdate', null=True)),
                ('salary', models.DecimalField(blank=True, db_column='Salary', decimal_places=0, max_digits=18, null=True)),
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('jobid', models.ForeignKey(blank=True, db_column='JobId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newapp.jobs')),
            ],
            options={
                'db_table': 'EmployeeData',
                'managed': True,
            },
        ),
    ]
