# Generated by Django 5.0.2 on 2025-09-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='descar',
        ),
    ]
